### ISSUE TITLE
Interest in loading certain data

### ISSUE THREAD

**Issue by qbarbier** [ebecht/hypergate#2]
Hi M. Becht,

Thank you for your tools and the tutorial.
I have some question about the data used in your demo.

The Labels vector seems to be never used in your analyse, you don't need the "good answer" in your algorithme ?

Is it more interesting to put a lot of markers that may have no interest or little of which we know the interest in a gating strategies ?

Do you know the maximum size on input file ?

Best regards,
Quentin Barbier

**Comment by ebecht** [comment]
Hello Quentin,

The labels are indeed not used in our tutorial. These would (arguably) be the ground truth for clustering methods or dimensionality reduction methods, but in our case we are rather interested in computing gating strategies. In our [preprint](https://www.biorxiv.org/content/early/2018/03/08/278796) we show that our tool's outputs are usually consistent with the gating strategies used to create these labels. You can try to use the algorithm on these labels.

In terms of input I usually throw everything in, maybe excluding channels used in pre-gating steps (e.g. CD45 if you gated on CD45+ immune cells beforehand). Other channels that should be excluded are Time, barcoding channels if any. Cell length and DNA content are usually not informative or relevant for further experiments (e.g. if you use FACS you can't directly replicate the cell length data from the CYToF), so I usually exclude them too.

For the input size it will depend on the amount of RAM you have available as well as the dimensionality of the dataset. If RAM is an issue I'd suggest uniform random downsampling of 1000 cells of the cluster of interest and a corresponding amount (say 99000 if the cluster of interest has a 1% frequency in the sample) from the rest of the cells.

Thanks for your feedbacks and feel free to let me know if you need further clarification or encounter other issues.

**Comment by SamGG** [comment]
Hi,
I think his Q/A is very interesting. It should be valuable to put it in the vignette, may be a "notes" section.
The graphical selection corresponds mainly to pop 8, ie Eosinophils, what could be more understandable from a biological point of view. 
```
table(gate_vector, Samusik_01_subset$labels)
# population name
# 1 B-cell Frac A-C (pro-B cells)
# 2 Basophils
# 3 CD4 T cells
# 4 CD8 T cells
# 5 Classical Monocytes
# 6 CLP
# 7 CMP
# 8 Eosinophils
# 9 gd T cells
# 10 GMP
# 11 HSC
# 12 IgD- IgMpos B cells
# 13 IgDpos IgMpos B cells
# 14 IgM- IgD- B-cells
# 15 Intermediate Monocytes
# 16 Macrophages
# 17 mDCs
# 18 MEP
# 19 MPP
# 20 NK cells
# 21 NKT cells
# 22 Non-Classical Monocytes
# 23 pDCs
# 24 Plasma Cells
```
This cluster sounds also the best aggregated subset on this tsne plot.
```
# Define cluster colors (here there are 30 colors) from Nowicka et al F1000
color_clusters <- c("#DC050C", "#FB8072", "#1965B0", "#7BAFDE", "#882E72",
  "#B17BA6", "#FF7F00", "#FDB462", "#E7298A", "#E78AC3",
  "#33A02C", "#B2DF8A", "#55A1B1", "#8DD3C7", "#A6761D",
  "#E6AB02", "#7570B3", "#BEAED4", "#666666", "#999999",
  "#aa8282", "#d4b7b7", "#8600bf", "#ba5ce3", "#808000",
  "#aeae5c", "#1e90ff", "#00bfff", "#56ff0d", "#ffff00")

plot(Samusik_01_subset$tsne, pch = 16, cex = 0.5, 
     col = color_clusters[as.factor(Samusik_01_subset$labels)])
```
![samusik_subset_tsne_colored](https://user-images.githubusercontent.com/3333348/44416180-891c7b00-a572-11e8-88fb-0e93f96f88ac.png)

**Comment by ebecht** [comment]
Thanks. I added a note as suggested and the vignette now covers your additions of hgate_info
