### ISSUE TITLE
How to select channels for re-optimization

### ISSUE THREAD

**Issue by ramay** [ebecht/hypergate#7]
Hi Etienne,
I have used hypergate on a dataset I am currently analyzing and have some questions about how to interpret the results. I tried emailing you as it is not an issue with the code but the email bounced back.

I have a dataset with four conditions and I have clustered the data with FLOWSOM. I performed differential cell population analysis and the clusters that were significantly different in the two populations, I tried to use hypergate to find out the gating strategy.

I have attached the output of hgate_info() 

<img width="888" alt="hg_outpt" src="https://user-images.githubusercontent.com/4459835/56232106-3b8eda00-603d-11e9-867a-d8aeb2ff7350.png">

So looking at the deltaF’s should I take out channels where deltaF is very small < 0.001 and re-optimize gating or re-run hypergate? I don't know how to make sense of this data as negative and positive populations of the markers are included here.

Thanks!
Hena

**Comment by ebecht** [comment]
Hi @ramay and thank you for your interest in this package!

Sorry about the bounced e-mail, I realized there was a typo in my e-mail address... It should be fixed now.

Delta-F is a measure of how the F score gets degraded when the channel is removed from the gating strategy. Thus, a high delta F means the channel is important to the gating strategy, while a low delta F means the channel can be safely ignored without impacting performance too much. You should therefore select the highest scoring parameters. In my experience, deltaF>0.01 usually leads to reasonable results so you could start with that. You can also plot a histogram of the vector of deltaF scores and visually assess a cutpoint.

I see that some threshold are negative and the data looks like it originates from a CyTOF. Negative values are not real in CyTOF as far as I know, and are usually obtained by uniform randomization of 0s into the [-1,0] interval. Sadly this is something hypergate is not aware of and it will try to cut below 0 and select thresholds there if it improves the results. Therefore it may be useful to revert randomization before running hypergate. You could do so by first running `subset_tsne[subset_tsne<0]=0`. That of course only applies if these negative values are indeed artificial.

Hopefully that will help!
Best,

**Comment by ramay** [comment]
Thanks a lot!
Yes, the data is from CyTOF and I had added a randomization of 0s [-1,0]. I will take that out and try out your suggestions.

Hena

**Comment by ebecht** [comment]
I'm closing the issue for now, feel free to reopen if there is any additional need for discussion
