### ISSUE TITLE
Missing channels after running hypergate?

### ISSUE THREAD

**Issue by sarahhcarl** [ebecht/hypergate#8]
Hi there,

I'm interested in using hypergate on some CyTOF data. I tested it out on my dataset using 36 channels as input, and the results I got back only contained 30 channels. I'm wondering what happened to the missing 6 - is there an implicit filtering step that would exclude them if their contribution is below a certain threshold?

Thanks for your help!

Best,
Sarah

**Comment by ebecht** [comment]
Hi @sarahhcarl and thank you for trying out hypergate,

There is no implicit filtering.

I think this could happen if two columns of your input matrix have the same names. You could try to set `colnames(xp)=make.names(colnames(xp))` (where `xp` is your input matrix) to make sure column names are unique?

Please let me know if that helped!
Best,
Etienne

**Comment by sarahhcarl** [comment]
Hi Etienne,

Thanks for the suggestion - however, I tried running `make.names()` (which added an "X" to the front of my variable names, as they started with a digit), but the results were the same. I also tested using the same expression matrix but a different selection vector, and in the end I only got back 28 channels in the hypergate results. I'm still not sure what could be causing it.

If you have any other thoughts, I'd be happy to hear!
Best,
Sarah

**Comment by SamGG** [comment]
Hi,
make.names() does not make unique column names by default. You have to add `unique = TRUE`, i.e.
`make.names(colnames(xp), unique = TRUE)`. This command will suffix the duplicated column names, highlighting duplication. Alternatively, you could use the duplicated function:
```
cnames = colnames(xp)
cnames[duplicated(cames)]
```
Best.

**Comment by sarahhcarl** [comment]
Hi Etienne,

Sorry, I should have clarified, all of my column names are unique (I've triple checked). That also wouldn't explain why I get a different number of channels back with different gate vectors, even when using the same expression matrix (with the same column names).

Cheers,
Sarah

**Comment by SamGG** [comment]
I think you should prepare some data to share with Etienne.
Samuel

**Comment by ebecht** [comment]
Indeed some data would be helpful to figure out what is happening.

Also, are you talking about the `active_channels` element of the result from an `hypergate` call? This should in general be shorter than the total number of channels, and if not most channels should have very small contributions and should be ignored.

Best
Etienne

**Comment by sarahhcarl** [comment]
Hi Etienne and Samuel,

It looks like it is the `active_channels` that I was seeing (at least the number of channels is consistent). I am using the functions `hgate_info`, `hgate_rule`, and `hgate_pheno` - should these return only the active channels?

If that's the case then problem solved :). It would be useful to add some more details to the documentation of these functions, though, so that users can know what to expect in the output. It would also be great to know exactly how the active channels are selected.

Best,
Sarah

**Comment by ebecht** [comment]
Yes it is expected that these functions only return the active channels are other channels have no impact on the gating strategy.

Best,
Etienne
